name: grafonnix-converter
version: 0.1.0
github: divnix/grafonnix-converter
license: MIT
license-file: LICENSE
synopsis: Convert grafana json dashboards to grafonnix expressions
author: Parthiv Seetharaman
maintainer: parthivs@myrdd.info
category: Distribution, Nix


ghc-options:
  - -Wall

dependencies:
  - aeson >= 2.0
  - aeson-better-errors >= 0.9.1.1
  - async-pool == 0.9.*
  - base == 4.*
  - bytestring == 0.10.*
  - containers >= 0.5 && < 0.7
  - data-fix >= 0.0.7 && < 0.4
  - directory == 1.3.*
  - filepath == 1.4.*
  - hnix == 0.16.0
  - mtl == 2.2.*
  - prettyprinter >= 1.2 && < 1.8
  - process >= 1.4
  - protolude ^>= 0.3
  - regex-tdfa ^>= 1.3
  - stm > 2.4.0 && < 2.6.0.0
  - scientific > 0.3.3.0 && < 0.4
  - text == 1.2.*
  - transformers == 0.5.*
  - unordered-containers == 0.2.*
  - optparse-applicative >= 0.16 && < 0.17

executables:
  grafonnix-converter:
    main: Main.hs
    default-extensions:
      - OverloadedStrings
